export const feelings = [
    {
        id: 1,
        name: 'Happy',
        icon: 'happy',
        color: '#FFD700',
    },
    {
        id: 2,
        name: 'Sad',
        icon: 'sad',
        color: '#1E90FF',
    },
    {
        id: 3,
        name: 'Angry',
        icon: 'angry',
        color: '#DC143C',
    },
    {
        id: 4,
        name: 'Anxious',
        icon: 'anxious',
        color: '#FF4500',
    },
    {
        id: 5,
        name: 'Stressed',
        icon: 'stressed',
        color: '#FF00FF',
    },
    {
        id: 6,
        name: 'Confused',
        icon: 'confused',
        color: '#FFA500',
    },
    {
        id: 7,
        name: 'Bored',
        icon: 'bored',
        color: '#808080',
    },
    {
        id: 8,
        name: 'Tired',
        icon: 'tired',
        color: '#008000',
    },
    {
        id: 9,
        name: 'Lonely',
        icon: 'lonely',
        color: '#0000FF',
    },
    {
        id: 10,
        name: 'Nervous',
        icon: 'nervous',
        color: '#FFFF00',
    },
    {
        id: 11,
        name: 'Shy',
        icon: 'shy',
        color: '#FF69B4',
    },
    {
        id: 12,
        name: 'Frustrated',
        icon: 'frustrated',
        color: '#000080',
    },
    {
        id: 13,
        name: 'Insecure',
        icon: 'insecure',
        color: '#FFC0CB',
    },
    {
        id: 14,
        name: 'Depressed',
        icon: 'depressed',
        color: '#800080',
    },
    {
        id: 15,
        name: 'Hopeless',
        icon: 'hopeless',
        color: '#800000',
    },
    {
        id: 16,
        name: 'Guilty',
        icon: 'guilty',
        color: '#FF0000',
    },
    {
        id: 17,
        name: 'Embarrassed',
        icon: 'embarrassed',
        color: '#008080',
    },
    {
        id: 18,
        name: 'Ashamed',
        icon: 'ashamed',
        color: '#FF6347',
    },
    {
        id: 19,
        name: 'Envious',
        icon: 'envious',
        color: '#00FF00',
    },
    {
        id: 20,
        name: 'Jealous',
        icon: 'jealous',
        color: '#00FFFF',
    },
    {
        id: 21,
        name: 'Proud',
        icon: 'proud',
        color: '#000000',
    },
    {
        id: 22,
        name: 'Excited',
        icon: 'excited',
        color: '#FFA07A',
    },
    {
        id: 23,
        name: 'Surprised',
        icon: 'surprised',
        color: '#FFDAB9',
    },
    {
        id: 24,
        name: 'Disgusted',
        icon: 'disgusted',
        color: '#F0E68C',
    },
    {
        id: 25,
        name: 'Disappointed',
        icon: 'disappointed',
        color: '#ADD8E6',
    },
    {
        id: 26,
        name: 'Determined',
        icon: 'determined',
        color: '#90EE90',
    },
    {
        id: 27,
        name: 'Relieved',
        icon: 'relieved',
        color: '#FFB6C1',
    },
    {
        id: 28,
        name: 'Calm',
        icon: 'calm',
        color: '#E0FFFF',
    },
    {
        id: 29,
        name: 'Content',
        icon: 'content',
        color: '#F0FFF0',
    },
    {
        id: 30,
        name: 'Inspired',
        icon: 'inspired',
        color: '#FFFAF0',
    },
    {
        id: 31,
        name: 'Hopeful',
        icon: 'hopeful',
        color: '#F5F5DC',
    },
];